Fix #94. --squash
Sun 14 Jan 2024 6:23 PM: It required 19 commits to make this work... Actually, 2 but that’s another area of changes.

#94: Fixed at 7:<=12 PM on Sat 13 Jan 2024
	# Running the “GitHub Pages” workflow results an error
	## What
	The problem is that GitHub Actions no not allow uploading an artifact which name contains the “"” character.

	So there are 2 solutions:

	1. Rename files;
	2. Update the workflow.

	Updating the workflow also has 2 opportunities:

	1. Checking out only packages that need to be build;
	2. Uploading only packages that need to be uploaded.

	> Updated at 5:55 PM on Fri 12 Jan 2024 ↓

	```
	Error: Artifact path is not valid: /script/bash/00-lint("package-lock.json").bash. Contains the following character:  Double quote "
	```

	#bug
	@VladimirCreator
	{ "created_at": "2024-01-11T13:06:15Z" }

@_r__-for-a-comment @crud-for-a-x @cru_-for-an-application @cv @exam-for-december-2022 @just-a-card @x

#issue #package

Thu 11 Jan 2024
	- 3:53 PM Get rid of .env.@_r__-for-a-comment
		> 3:54 PM Undo.
	- 3:58 PM Update .env.@cru_-for-an-application
	- 3:59 PM Update .env.@crud-for-a-x
	- 4:00 PM Update .env.@cv
	- 4:02 PM Update .env.@exam-for-december-2022
	- 4:03 PM Update .env.@just-a-card
	- 4:03 PM Update .env.@just-a-form
	- 4:04 PM Update .env.@x
	- 4:05 PM...4:08 PM Update /zGitHubAndYouShouldIgnoreThisDirectory/dynamic/*.
	- 4:13 PM Add the “Topics” block.
		> Update Readme.md.
	- 4:25 PM Rename all vite-env.d.ts to env.d.ts.
	- 5:58 PM...5:59 PM Create /script/bash/05-sort("package.json").

Fri 12 Jan 2024
	- 11:38 AM Create /Draft/Package/.
	- 11:39 AM Create /Draft/Package/index.css.
	- 11:39 AM Create /Draft/Package/App.css.
	- 2:05 PM Create /.github/actions/action/*.yaml.
	- 2:06 PM Use `github.ref_name` instead of `inputs.ref`.
	- 2:07 PM Get rid of `runs-on` and use `ubuntu-latest`.
	- Sat 13 Jan 2024 6:37 PM Create /.devcontainer/devcontainer.json.

Sat 13 Jan 2024
	- 6:51 PM `ref` already uses the branch I select.
	- 6:52 PM...: PM checkout now uses sparse-checkout as input
	- 6:53 PM `repository` is now `shared`
	- 6:54 PM Bump actions/upload-artifact@3 to @4
	- 6:55 PM Bump actions/download-artifact@2 to @4
	- 6:55 PM Bump actions/setup-node@3 to @4
	- 6:56 PM Bump actions/deploy-pages@2 to @4
	- 6:50 PM Create /.github/workflows/deploy.yaml.

To Do:
Tue 9 Jan 2024
	- [x->4:54 PM Thu 11 Jan 2024] 10:30 AM Replace `div` with `article` in ProjectCard.tsx.
   - [] 10:34 AM Add animation of appearing of a command menu.
                 It will slide out from the main block at center.
	- [] 10:35 AM Change the text when pressing `⌘` + `j`.

Wed 10 Jan 2024
	- [] 11:02 AM...11:05 AM Add the “Table of Contents” on the left of the main block at center. It will look like a list of groups where each group includes an icon and text. Examples: □ Read Books

Fri 12 Jan 2024
	- [] 2:41 PM Use power of Workflow commands.

Sat 13 Jan 2024
	- [6:49 PM] 5:56 PM Add the “PureScript” column in the “Overview” block
		> Update /Readme.md.
	- [] 9:21 PM Create .github/ISSUE_TEMPLATE/

On branch fix-96-running-the-github-pages-workflow-results-an-error
Changes to be committed:
	- modified:   .github/workflows/build.yaml
	- new file:   .github/workflows/deploy.yaml
	- modified:   .github/workflows/github-pages.yaml
	- new file:   Draft/Package/App.css
	- renamed:    Draft/App.tsx -> Draft/Package/App.tsx
	- new file:   Draft/Package/index.css
	- modified:   Readme.md
	- modified:   _r__-for-a-comment/.env
	- modified:   cru_-for-an-application/.env
	- modified:   crud-for-a-x/.env
	- modified:   cv/.env
	- modified:   cv/index.html
	- modified:   cv/src/App.tsx
	- modified:   cv/src/Component/Header.tsx
	- modified:   cv/src/Component/ProjectSection.tsx
	- modified:   cv/src/Component/UI/Card.tsx
	- renamed:    cv/src/vite-env.d.ts -> cv/src/env.d.ts
	- modified:   exam-for-december-2022/.env
	- modified:   just-a-card/.env
	- renamed:    just-a-card/vite-env.d.ts -> just-a-card/src/env.d.ts
	- modified:   just-a-form/.env
	- new file:   "script/bash/05-sort(\"package.json\").bash"
	- modified:   "script/swift/00-format(\"package-lock.json\").swift"
	- modified:   "script/swift/01-ensure(\"*\", \"does not have leading spaces\").swift"
	- modified:   "script/swift/02-ensure(\"*\", \"does not have trailing whitespaces\").swift"
	- modified:   "script/swift/03-ensure(\"*\", \" last 2 characters equal a new line character\").swift"
	- modified:   script/swift/essentials.swift
	- modified:   x/.env
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/_r__-for-a-comment.gif -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/_r__-for-a-comment/_r__-for-a-comment.gif
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/_r__-for-a-hotel.mov -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/_r__-for-a-hotel/_r__-for-a-hotel.mov
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/cru_-for-an-application.gif -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/cru_-for-an-application/cru_-for-an-application.gif
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/crud-for-a-x.gif -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/crud-for-a-x/crud-for-a-x.gif
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/exam-for-december-2022.gif -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/exam-for-december-2022/exam-for-december-2022.gif
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/shade-explorer.gif -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/shade-explorer/shade-explorer.gif
	- renamed:    zGitHubAndYouShouldIgnoreThisDirectory/dynamic/x.gif -> zGitHubAndYouShouldIgnoreThisDirectory/dynamic/x/x.gif